[[headers]]
   for = "/*"
   [headers.values]
    Cache-Control = "no-transform"
    Content-Security-Policy = "default-src 'self';"
    frame-ancestors 'none';'''
    Upgrade-Insecure-Requests = "1"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
